"""empty message

Revision ID: 47c9f0c1e80c
Revises: 6d91bb2aefd3
Create Date: 2019-06-01 11:01:38.888807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c9f0c1e80c'
down_revision = '6d91bb2aefd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('bathrooms_str', sa.String(length=255), nullable=True))
    op.add_column('deal', sa.Column('bedrooms_str', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'bedrooms_str')
    op.drop_column('deal', 'bathrooms_str')
    # ### end Alembic commands ###
